openapi: 3.0.3
info:
  title: HimuOJ BFF Contracts
  version: 2.0.0
  description: BFF aggregate root API index. Aggregate endpoints are split by root YAML files.
paths: {}
x-aggregate-root-contracts:
  - openapi/problems.v1.yaml
  - openapi/submissions.v1.yaml
