openapi: 3.0.3
info:
  title: HimuOJ BFF Contracts
  version: 2.0.0
  description: BFF aggregate root API index. Aggregate endpoints are split by root YAML files.
  license:
    name: Proprietary
    url: https://himuoj.com/license
servers:
  - url: https://api.himuoj.local
    description: Placeholder base URL for contract validation.
paths: {}
x-aggregate-root-contracts:
  - openapi/objects.v1.yaml
  - openapi/problems.v1.yaml
  - openapi/submissions.v1.yaml
