openapi: 3.0.3
info:
  title: HimuOJ Problems Aggregate Contracts
  version: 2.0.0
  description: REST contracts for Problem aggregate root and TestCases entity.
  license:
    name: Proprietary
    url: https://himuoj.com/license
servers:
  - url: https://api.himuoj.local
    description: Placeholder base URL for contract validation.
security: []
tags:
  - name: Problems
    description: Problem aggregate root operations.
  - name: TestCases
    description: Test case entity operations under a problem.
paths:
  /api/v1/problems:
    get:
      tags:
        - Problems
      summary: List problems
      operationId: ListProblems
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - name: authorId
          in: query
          description: Filter by problem author.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Paged problem list.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedProblemSummaryResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Problems
      summary: Create problem
      operationId: CreateProblem
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProblemRequest'
      responses:
        '201':
          description: Problem created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/problems/{problemId}:
    get:
      tags:
        - Problems
      summary: Get problem detail
      operationId: GetProblemById
      parameters:
        - $ref: '#/components/parameters/ProblemId'
      responses:
        '200':
          description: Problem detail.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    patch:
      tags:
        - Problems
      summary: Update problem
      operationId: UpdateProblem
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProblemId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProblemRequest'
      responses:
        '200':
          description: Problem updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/problems/{problemId}/test-cases:
    get:
      tags:
        - TestCases
      summary: List test cases for a problem
      operationId: ListProblemTestCases
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProblemId'
        - name: includeHidden
          in: query
          description: Include hidden cases in result, requires admin privileges.
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Test case list.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestCaseListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - TestCases
      summary: Create test case for problem
      operationId: CreateProblemTestCase
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProblemId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTestCaseRequest'
      responses:
        '201':
          description: Test case created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestCaseDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/problems/{problemId}/test-cases/{testCaseId}:
    patch:
      tags:
        - TestCases
      summary: Update test case
      operationId: UpdateProblemTestCase
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProblemId'
        - $ref: '#/components/parameters/TestCaseId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTestCaseRequest'
      responses:
        '200':
          description: Test case updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestCaseDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - TestCases
      summary: Delete test case
      operationId: DeleteProblemTestCase
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProblemId'
        - $ref: '#/components/parameters/TestCaseId'
      responses:
        '204':
          description: Test case deleted.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    ProblemId:
      name: problemId
      in: path
      required: true
      schema:
        type: integer
        format: int64
        minimum: 1
      description: Problem identifier.
    TestCaseId:
      name: testCaseId
      in: path
      required: true
      schema:
        type: integer
        format: int64
        minimum: 1
      description: Test case identifier.
    Page:
      name: page
      in: query
      description: 1-based page number.
      schema:
        type: integer
        minimum: 1
        default: 1
    PageSize:
      name: pageSize
      in: query
      description: Page size.
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
  responses:
    BadRequest:
      description: The request payload or parameters are invalid.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    Unauthorized:
      description: Authentication is required.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    Forbidden:
      description: The current principal has no permission.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    NotFound:
      description: The requested resource does not exist.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    Conflict:
      description: The request conflicts with current state.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    InternalServerError:
      description: Unexpected server-side error.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
  schemas:
    ProblemSummary:
      type: object
      required:
        - id
        - title
        - timeLimitMs
        - memoryLimitKb
        - authorId
        - createdAt
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          minLength: 1
          maxLength: 256
        timeLimitMs:
          type: integer
          minimum: 1
        memoryLimitKb:
          type: integer
          minimum: 1
        authorId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
    ProblemDetail:
      allOf:
        - $ref: '#/components/schemas/ProblemSummary'
        - type: object
          required:
            - descriptionUploadId
          properties:
            descriptionUploadId:
              type: string
              minLength: 1
              maxLength: 1024
    CreateProblemRequest:
      type: object
      additionalProperties: false
      required:
        - title
        - descriptionUploadId
        - timeLimitMs
        - memoryLimitKb
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 256
        descriptionUploadId:
          type: string
          minLength: 1
          maxLength: 1024
        timeLimitMs:
          type: integer
          minimum: 1
        memoryLimitKb:
          type: integer
          minimum: 1
    UpdateProblemRequest:
      type: object
      additionalProperties: false
      minProperties: 1
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 256
        descriptionUploadId:
          type: string
          minLength: 1
          maxLength: 1024
        timeLimitMs:
          type: integer
          minimum: 1
        memoryLimitKb:
          type: integer
          minimum: 1
    TestCaseDetail:
      type: object
      required:
        - id
        - problemId
        - inputUploadId
        - expectedOutputUploadId
        - scoreWeight
        - isHidden
      properties:
        id:
          type: integer
          format: int64
        problemId:
          type: integer
          format: int64
        inputUploadId:
          type: string
          minLength: 1
          maxLength: 1024
        expectedOutputUploadId:
          type: string
          minLength: 1
          maxLength: 1024
        scoreWeight:
          type: integer
          minimum: 0
        isHidden:
          type: boolean
    CreateTestCaseRequest:
      type: object
      additionalProperties: false
      required:
        - inputUploadId
        - expectedOutputUploadId
        - scoreWeight
        - isHidden
      properties:
        inputUploadId:
          type: string
          minLength: 1
          maxLength: 1024
        expectedOutputUploadId:
          type: string
          minLength: 1
          maxLength: 1024
        scoreWeight:
          type: integer
          minimum: 0
        isHidden:
          type: boolean
    UpdateTestCaseRequest:
      type: object
      additionalProperties: false
      minProperties: 1
      properties:
        inputUploadId:
          type: string
          minLength: 1
          maxLength: 1024
        expectedOutputUploadId:
          type: string
          minLength: 1
          maxLength: 1024
        scoreWeight:
          type: integer
          minimum: 0
        isHidden:
          type: boolean
    PageMeta:
      type: object
      required:
        - page
        - pageSize
        - totalItems
        - totalPages
      properties:
        page:
          type: integer
          minimum: 1
        pageSize:
          type: integer
          minimum: 1
        totalItems:
          type: integer
          minimum: 0
        totalPages:
          type: integer
          minimum: 0
    PagedProblemSummaryResponse:
      type: object
      required:
        - items
        - meta
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProblemSummary'
        meta:
          $ref: '#/components/schemas/PageMeta'
    TestCaseListResponse:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TestCaseDetail'
    ProblemDetails:
      type: object
      required:
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          nullable: true
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
