openapi: 3.0.3
info:
  title: HimuOJ Submissions Aggregate Contracts
  version: 2.0.0
  description: REST contracts for Submission aggregate root and TestCaseResults entity.
  license:
    name: Proprietary
    url: https://himuoj.com/license
servers:
  - url: https://api.himuoj.local
    description: Placeholder base URL for contract validation.
tags:
  - name: Submissions
    description: Submission aggregate root operations.
paths:
  /api/v1/submissions:
    get:
      tags:
        - Submissions
      summary: List submissions
      operationId: ListSubmissions
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - name: userId
          in: query
          description: Filter by submitter.
          schema:
            type: integer
            format: int64
        - name: problemId
          in: query
          description: Filter by problem id.
          schema:
            type: integer
            format: int64
        - name: language
          in: query
          description: Filter by language key.
          schema:
            type: string
            maxLength: 32
        - name: status
          in: query
          description: Filter by judging status.
          schema:
            $ref: '#/components/schemas/JudgeStatus'
      responses:
        '200':
          description: Paged submission list.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedSubmissionSummaryResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Submissions
      summary: Create submission
      operationId: CreateSubmission
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubmissionRequest'
      responses:
        '202':
          description: Submission accepted for async judging.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionAcceptedResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/submissions/{submissionId}:
    get:
      tags:
        - Submissions
      summary: Get submission detail
      operationId: GetSubmissionById
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SubmissionId'
      responses:
        '200':
          description: Submission detail.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/submissions/{submissionId}/test-case-results:
    get:
      tags:
        - Submissions
      summary: List test case results of submission
      operationId: ListSubmissionTestCaseResults
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SubmissionId'
      responses:
        '200':
          description: Test case results for submission.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestCaseResultListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    SubmissionId:
      name: submissionId
      in: path
      required: true
      schema:
        type: integer
        format: int64
        minimum: 1
      description: Submission identifier.
    Page:
      name: page
      in: query
      description: 1-based page number.
      schema:
        type: integer
        minimum: 1
        default: 1
    PageSize:
      name: pageSize
      in: query
      description: Page size.
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
  responses:
    BadRequest:
      description: The request payload or parameters are invalid.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    Unauthorized:
      description: Authentication is required.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    Forbidden:
      description: The current principal has no permission.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    NotFound:
      description: The requested resource does not exist.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    UnprocessableEntity:
      description: Business rule validation failed.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    InternalServerError:
      description: Unexpected server-side error.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
  schemas:
    JudgeStatus:
      type: string
      enum:
        - Pending
        - Running
        - Accepted
        - WrongAnswer
        - TimeLimitExceeded
        - MemoryLimitExceeded
        - RuntimeError
        - CompilationError
        - SystemError
    SubmissionSummary:
      type: object
      required:
        - id
        - userId
        - problemId
        - language
        - status
        - maxTimeConsumedMs
        - maxMemoryConsumedKb
        - submittedAt
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        problemId:
          type: integer
          format: int64
        language:
          type: string
          minLength: 1
          maxLength: 32
        status:
          $ref: '#/components/schemas/JudgeStatus'
        maxTimeConsumedMs:
          type: integer
          minimum: 0
        maxMemoryConsumedKb:
          type: integer
          minimum: 0
        submittedAt:
          type: string
          format: date-time
    SubmissionDetail:
      allOf:
        - $ref: '#/components/schemas/SubmissionSummary'
        - type: object
          required:
            - codeUploadId
          properties:
            codeUploadId:
              type: string
              minLength: 1
              maxLength: 1024
    CreateSubmissionRequest:
      type: object
      additionalProperties: false
      required:
        - problemId
        - language
        - codeUploadId
      properties:
        problemId:
          type: integer
          format: int64
          minimum: 1
        language:
          type: string
          minLength: 1
          maxLength: 32
          example: cpp17
        codeUploadId:
          type: string
          minLength: 1
          maxLength: 1024
    SubmissionAcceptedResponse:
      type: object
      required:
        - submissionId
        - status
      properties:
        submissionId:
          type: integer
          format: int64
        status:
          $ref: '#/components/schemas/JudgeStatus'
    TestCaseResultDetail:
      type: object
      required:
        - id
        - submissionId
        - testCaseId
        - status
        - timeConsumedMs
        - memoryConsumedKb
      properties:
        id:
          type: integer
          format: int64
        submissionId:
          type: integer
          format: int64
        testCaseId:
          type: integer
          format: int64
        status:
          $ref: '#/components/schemas/JudgeStatus'
        timeConsumedMs:
          type: integer
          minimum: 0
        memoryConsumedKb:
          type: integer
          minimum: 0
        actualOutputUploadId:
          type: string
          nullable: true
          maxLength: 1024
        errorMessage:
          type: string
          nullable: true
          maxLength: 2048
    PageMeta:
      type: object
      required:
        - page
        - pageSize
        - totalItems
        - totalPages
      properties:
        page:
          type: integer
          minimum: 1
        pageSize:
          type: integer
          minimum: 1
        totalItems:
          type: integer
          minimum: 0
        totalPages:
          type: integer
          minimum: 0
    PagedSubmissionSummaryResponse:
      type: object
      required:
        - items
        - meta
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionSummary'
        meta:
          $ref: '#/components/schemas/PageMeta'
    TestCaseResultListResponse:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TestCaseResultDetail'
    ProblemDetails:
      type: object
      required:
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          nullable: true
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
